[build]
  base = "Portfolio"   # Specify the folder name where your project is located
  command = "npm run build"   # Production build command
  publish = "Portfolio/dist"   # The 'dist' folder where Vite builds the app

[dev]
  command = "npm run dev"     # Development server command

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true
