[build]
  command = "npm run build"   # Production build command
  publish = "dist"            # Output directory for Vite (production build)

[dev]
  command = "npm run dev"     # Development server command
  
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true
